version: "3.7"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    networks:
      - micro
    ports:
      - 8500:8500
    # volumes:
    #   - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - micro
    ports:
    - 9998:9998
    - 9999:9999

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - micro
    ports:
      - 3000:3000
    # volumes:
    #   - grafana:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    networks:
      - micro
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - micro
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  prometheus:
    build: ./prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - micro
    ports:
      - 9090:9090
    # volumes:
    #   - prometheus:/prometheus

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - micro
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - micro
    ports:
      - 5341:80
    # volumes: 
    #   - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    networks:
      - micro
    ports:
      - 8200:8200

networks:
  micro:
    name: micro-network

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  postgres:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  # seq:
  #   driver: local
  