global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'customers-service'
    static_configs:
      - targets: ['host.docker.internal:5010']

  - job_name: 'deliveries-service'
    static_configs:
      - targets: ['host.docker.internal:5020']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['host.docker.internal:5030']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']